# PostgREST Production Deployment
# RESTful API server powered by PostgreSQL
#
# This is the main app spec — auto-detected by DigitalOcean App Platform
#
# What it does:
#   1. Provisions a production PostgreSQL 16 database
#   2. Runs db-init job: creates tables + loads 451K H1B records
#   3. Starts PostgREST service with read-only 'anon' role
#
# Deploy: Connect GitHub repo, DigitalOcean picks up this file automatically

name: postgrest-app
region: nyc

databases:
- name: postgrest-db
  engine: PG
  version: "16"
  production: true
  cluster_name: postgrest-db

jobs:
- name: db-init
  kind: PRE_DEPLOY
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb

  github:
      repo: gary-limo/postgrest-appplatform
      branch: main
      deploy_on_push: true

  dockerfile_path: Dockerfile

  envs:
    - key: PGHOST
      value: ${postgrest-db.HOSTNAME}
    - key: PGPORT
      value: ${postgrest-db.PORT}
    - key: PGDATABASE
      value: ${postgrest-db.DATABASE}
    - key: PGUSER
      value: ${postgrest-db.USERNAME}
    - key: PGPASSWORD
      value: ${postgrest-db.PASSWORD}
    - key: PGSSLMODE
      value: require

  run_command: "psql \"${postgrest-db.DATABASE_URL}\" -f /app/config/init.production.sql && psql \"${postgrest-db.DATABASE_URL}\" -f /app/config/load_h1b_data_production.sql"

services:
- name: postgrest-service
  github:
      repo: gary-limo/postgrest-appplatform
      branch: main
      deploy_on_push: true

  dockerfile_path: Dockerfile
  internal_ports:
  - 3000
  instance_size_slug: apps-d-1vcpu-1gb

  autoscaling:
    min_instance_count: 1
    max_instance_count: 3
    metrics:
      cpu:
        percent: 85

  health_check:
    http_path: /
    initial_delay_seconds: 40
    period_seconds: 10
    timeout_seconds: 3
    success_threshold: 1
    failure_threshold: 3

  envs:
    # PostgreSQL connection
    - key: PGRST_DB_URI
      value: ${postgrest-db.DATABASE_URL}

    # Database schema to expose via API
    - key: PGRST_DB_SCHEMAS
      value: api

    # Read-only role (blocks POST/PATCH/DELETE)
    - key: PGRST_DB_ANON_ROLE
      value: anon

    # Server configuration
    - key: PGRST_SERVER_HOST
      value: "0.0.0.0"

    - key: PGRST_SERVER_PORT
      value: "3000"

    - key: PGRST_LOG_LEVEL
      value: info

- name: frontend
  github:
      repo: gary-limo/postgrest-appplatform
      branch: main
      deploy_on_push: true

  source_dir: frontend
  
  build_command: npm install && npm run build
  run_command: npm start
  
  http_port: 3000
  instance_size_slug: apps-d-1vcpu-1gb

  envs:
    # Backend URL for Next.js rewrites (internal service)
    - key: POSTGREST_INTERNAL_URL
      value: http://postgrest-service:3000
    
    # Fix npm peer dependency conflicts
    - key: npm_config_legacy_peer_deps
      value: "true"
