# PostgREST Production Template
# RESTful API server powered by PostgreSQL
# Production setup with dedicated 'api' schema and 'anon' role
#
# Prerequisites:
# - Create database: doctl databases create postgrest-db --engine pg --version 16 --region <region> --size db-s-1vcpu-1gb
#
# Deploy with: doctl apps create --spec .do/production-app.yaml

name: postgrest-app-prod
# Optionally you can chose a region where the deployment will be hosted
# Otherwise, DO will chose the nearest region for you in the wizard
# region: nyc

databases:
- name: postgrest-db
  engine: PG
  version: "16"
  production: true
  cluster_name: postgrest-db

jobs:
- name: db-init
  kind: PRE_DEPLOY
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb

  github:
      repo: gary-limo/postgrest-appplatform
      branch: main
      deploy_on_push: true

  dockerfile_path: Dockerfile

  envs:
    - key: PGHOST
      value: ${postgrest-db.HOSTNAME}
    - key: PGPORT
      value: ${postgrest-db.PORT}
    - key: PGDATABASE
      value: ${postgrest-db.DATABASE}
    - key: PGUSER
      value: ${postgrest-db.USERNAME}
    - key: PGPASSWORD
      value: ${postgrest-db.PASSWORD}
    - key: PGSSLMODE
      value: require

  run_command: "psql -f /app/config/init.production.sql && psql -f /app/config/load_h1b_data_production.sql"

services:
- name: postgrest-service
  # Build from source (Dockerfile in repository root)
  github:
      repo: gary-limo/postgrest-appplatform
      branch: main
      deploy_on_push: true

  # Container configuration
  dockerfile_path: Dockerfile
  http_port: 3000
  # instance_count: 1 # Not needed if autoscaling is enabled
  instance_size_slug: apps-d-1vcpu-1gb

  # Autoscaling configuration
  autoscaling:
    min_instance_count: 1
    max_instance_count: 3
    metrics:
      cpu:
        percent: 80

  # Health check configuration
  health_check:
    http_path: /
    initial_delay_seconds: 40
    period_seconds: 10
    timeout_seconds: 3
    success_threshold: 1
    failure_threshold: 3

  # Environment variables
  envs:
    # PostgreSQL connection (automatically injected by App Platform)
    - key: PGRST_DB_URI
      value: ${postgrest-db.DATABASE_URL}

    # Database schema to expose via API
    - key: PGRST_DB_SCHEMAS
      value: public

    # Anonymous role for unauthenticated requests (read-only, blocks POST/PATCH/DELETE)
    - key: PGRST_DB_ANON_ROLE
      value: anon

    # Server configuration
    - key: PGRST_SERVER_HOST
      value: "0.0.0.0"

    - key: PGRST_SERVER_PORT
      value: "3000"

    # Logging level
    - key: PGRST_LOG_LEVEL
      value: info

    # Template tracking
    - key: APPPLAT_BASE_TEMPLATE
      value: postgrest

    - key: APPPLAT_TEMPLATE_TYPE
      value: production

    - key: APPPLAT_TEMPLATE_COMMIT_SHA
      value: ${_self.COMMIT_HASH}
